# This is a basic workflow to help you get started with Actions

name: 天气机器人

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 21 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: bash ./weather.sh
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      id: cutime
      with:
        timezone: Asia/Shanghai
    - name: Get current time
      uses: gerred/actions/current-time@master
      id: current-time
    - name: 'Get Date'
      run: echo "REPORT_DAT=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" 
      id: datee
    - name: 'Send mail'
      uses: dawidd6/action-send-mail@v2.2.3
      env:
        REPORT_DATE: "${{ steps.cutime.time }}"
      with:
          server_address: smtp.mxhichina.com
          server_port: 587
          username: ${{ secrets.USERNAME }} 
          password: ${{ secrets.PASSWORD }}
          subject: HeBei Weather Report (${{steps.current-time.outputs.time}})
          # Literal body:
   
          # Read file contents as body:
          body: file://result.html
          to: news@aiepn.com
          from: 天气预报@Sean
          content_type: text/html
        
